### ISSUE TITLE
link for "CUBI project repository layout guidelines"

### ISSUE THREAD

**Issue by FerallOut** [core-unit-bioinformatics/knowledge-base#6]
The link in 
`Preliminaries
- set the project name according to "the CUBI naming standards"` 
 
should point to "https://github.com/core-unit-bioinformatics/knowledge-base/wiki/Naming-and-style"

instead it points to  an empty file at this address:
"https://github.com/core-unit-bioinformatics/knowledge-base/wiki/Naming-and-style.md"

**Comment by ptrebert** [comment]
ok, this is the process, but trivialities like this would be faster to fix right away instead of opening an issue ...

fixed in f23e1c8
